# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check dist/ and commit them

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request_target:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Rebuild the dist/ directory
        run: yarn prepare

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'dist'
          message: 'Add new /dist'
          default_author: github_actions
